### ISSUE TITLE
the app can not work after repack

### ISSUE THREAD

**Issue by Kcrafting** [jakev/xamarin-assembly-store-unpack#11]
i follow the step to update my app(one of it's dll,i lost the file),but the app crash when i click the app,is there some possibly reason for my problem?

**Comment by rob-X1** [comment]
Assuming you are talking about an Android app: have you checked if the problem is really related to pyxamstore repacking? 

May be just resigning is enough to cause the "crash". Some apps check their app signature or use other ways to check that the have not been modified and if the detect a modification just terminate itself.

**Comment by Kcrafting** [comment]
i have found two file in the blob file,one is projectname.dll,another is projectnameandroid.dll,i modify the  projectnameandroid.dll with dnspy,i only modify the request url,i use apktoolkit for all process,decompile,compress blob file,modify file,repack blob file,replace file,compile app,align zip,sign app,after all process,now the app could  be install and open,now it's not crash,but there is no ui displayed,only black screen,i don't know why

**Comment by serrapa** [comment]
@jakev @rob-X1 I still have the same problem, the app crash after repacking... 

I did some tests, since I am working also with a split apk:
- I exported all the apks from the device.
- I used apktool to decompile the app: 
  - `apktool d base.apk -o base`
- I recompiled the app again with apktool just to make sure the repacking and resigning process were done well:
  - `apktool b base -o apks/base.apk`
  - `uber-apk-signer -a apks/`
  - `adb install-multiple base.apk split_config.*.apk`
- The app works perfectly...
- I used pyxamstore (I did nothing to edit to the app just to know if the packing phase was not affected):
  - pyxamstore unpack -d <path>/base/unknown/assemblies/
  - pyxamstore pack -c assemblies.json
  - copied the new assemblies.blob e assemblies.manifest <path>/base/unknown/assemblies/
- I recompiled the app again with apktool:
  - `apktool b base -o apks/patched_base.apk`
  - `uber-apk-signer -a apks/`
  - `adb install-multiple patched_base.apk split_config.*.apk`

When I start the app, it crashes.. without using pyxamstore, it works, so I believed the root cause may be due to pyxamstore... in both cases the app signature is different from the original, I dont think the app has integrity checks...  

When launching the app, i see many errors in the logcat view:

```
03-07 12:00:35.596 12954 12954 E AndroidRuntime: android.content.res.Resources$NotFoundException: Drawable **__redacted__**:drawable/abc_switch_thumb_material with resource ID #0x7f08004c
03-07 12:00:35.596 12954 12954 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_switch_thumb_material.xml from drawable resource ID #0x7f08004c
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:879)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:1002)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:992)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:931)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:810)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:1012)
03-07 12:00:35.596 12954 12954 E AndroidRuntime: 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:522)
...
03-07 12:00:35.603 12954 12954 I MonoDroid: UNHANDLED EXCEPTION:
03-07 12:00:35.616 12954 12954 I MonoDroid: Android.Content.Res.Resources+NotFoundException: Drawable **__redacted__**:drawable/abc_switch_thumb_material with resource ID #0x7f08004c ---> Android.Content.Res.Resources+NotFoundException: File res/drawable/abc_switch_thumb_material.xml from drawable resource ID #0x7f08004c ---> Org.XmlPull.V1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
03-07 12:00:35.616 12954 12954 I MonoDroid:    --- End of inner exception stack trace ---
03-07 12:00:35.616 12954 12954 I MonoDroid:    --- End of inner exception stack trace ---
03-07 12:00:35.616 12954 12954 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <20118b589b464e28831b3f15512b93dc>:0
03-07 12:00:35.616 12954 12954 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.FinishCreateInstance (System.String constructorSignature, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0004f] in <20118b589b464e28831b3f15512b93dc>:0
03-07 12:00:35.616 12954 12954 I MonoDroid:   at AndroidX.AppCompat.Widget.SwitchCompat..ctor (Android.Content.Context context) [0x0007b] in <5db77ff9ed134989b3f7a2a2547a31e8>:0
03-07 12:00:35.616 12954 12954 I MonoDroid:   at Xamarin.Forms.Platform.Android.AppCompat.SwitchRenderer.CreateNativeControl () [0x00006] in <8a8198b5c4654c60b09c3bf93303bda9>:0
03-07 12:00:35.616 12954 12954 I MonoDroid:   at Xamarin.Forms.Platform.Android.AppCompat.SwitchRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00036] in <8a8198b5c4654c60b09c3bf93303bda9>:0
....
03-07 12:00:35.617 12954 12954 I MonoDroid:   at Android.Views.View.n_OnMeasure_II (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00008] in <0a035028ff7f440abcee06abe6ca27ef>:0
03-07 12:00:35.617 12954 12954 I MonoDroid:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V (_JniMarshal_PPII_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.Int32 p0, System.Int32 p1) [0x00005] in <0a035028ff7f440abcee06abe6ca27ef>:0
03-07 12:00:35.617 12954 12954 I MonoDroid:   --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
03-07 12:00:35.617 12954 12954 I MonoDroid: android.content.res.Resources$NotFoundException: Drawable **__redacted__**:drawable/abc_switch_thumb_material with resource ID #0x7f08004c
03-07 12:00:35.617 12954 12954 I MonoDroid: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_switch_thumb_material.xml from drawable resource ID #0x7f08004c
03-07 12:00:35.617 12954 12954 I MonoDroid: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:879)
03-07 12:00:35.617 12954 12954 I MonoDroid: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
03-07 12:00:35.617 12954 12954 I MonoDroid: 	at android.content.res.Resources.loadDrawable(Resources.java:1002)
03-07 12:00:35.617 12954 12954 I MonoDroid: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:992)
03-07 12:00:35.617 12954 12954 I MonoDroid: 	at android.content.res.Resources.getDrawable(Resources.java:931)
```

**Comment by serrapa** [comment]
Sorry my bad.. I found the error... I was related to something wrong on the resources. To fix I just needed to launch apktool with the `-r` flag:
- apktool d base.apk -r -o base

Then, it worked.
